### ISSUE TITLE
Static frontpage

### ISSUE THREAD

**Issue by jsonnull** [jsonnull/aleamancer#73]
Tracking issue for a static frontpage.

## Background

Currently the app is served at a single endpoint, `/index.html`. The goal is to serve a statically rendered `index.html` and direct logged-in users to a dynamic `/app.html`.

The redirect/rewrite scheme will be this:

**Server-side rewrites**
- `/` -> `/index.html`
- `/*` -> `/app.html`

**Breakdown for users and login state**
- `/` ->  User is served `index.html`, follows links to access logged-in home (`/games`)
- `/*` ->  User is served `app.html`, app waits for login state and redirects to `/login` if logged-out

## Todos:

- [ ] Separate index.html and app.html endpoints
- [ ] Modify Firebase hosting route configuration for new html endpoints
- [ ] Add code-splitting so homepage does not load non-essential components
- [ ] Statically render homepage during CI build
